### ISSUE TITLE
[common] 프로필 모달 외부 영역 클릭시 닫히도록

### ISSUE THREAD

**Issue by choichoijin** [DeliverBle/deliverble-frontend#86]
## ✨ Description
로그인 후 프로필 모달이 떴을 때 모달 외부 영역을 클릭할 경우에 모달이 닫힙니다. 

금방 끝날 거라 생각했는데 이거 때메 다른 진도가 안나가네용 help wanted 답니다 😭

저희 코드 중 외부 영역 클릭 시 닫히게 하는 로직을 사용하려고 했으나,
NavigationBar.tsx에서 프로필 모달은 커스텀 컴포넌트이기 때문에 useRef를 활용하는 데 어려움을 겪고 있습니다. ㅠㅠ 

`<ProfileModal />`에 직접 ref를 달 경우 해당 오류가 뜹니다.
<img width="443" alt="스크린샷 2022-08-01 오후 1 42 35" src="https://user-images.githubusercontent.com/99077953/182073844-7a886634-22df-4c94-b3c8-509fc537541c.png">

찾아보니 함수 컴포넌트는 ref attribute가 존재하지 않는다던데, `forwardRef`를 사용해서 시도하는 데도 어려움을 겪고 있어요. 모달 영역을 특정하는 좋은 방법이 있을까요?

## ✅ To Do List
- [x] 기능 구현

**Comment by 100Gyeon** [comment]
코드 봤는데 props를 통해 ref를 전달하지 않아도 해결할 수 있는 문제더라구요!
프로필 이미지(사람 아이콘 버튼)에 ref 하나 추가하고, useEffect 안의 if문에 조건 추가해서 해결했습니다 😉

**Comment by choichoijin** [comment]
> 코드 봤는데 props를 통해 ref를 전달하지 않아도 해결할 수 있는 문제더라구요! 프로필 이미지(사람 아이콘 버튼)에 ref 하나 추가하고, useEffect 안의 if문에 조건 추가해서 해결했습니다 😉

헐 감동 실화.. 🙉 저 div는 ref를 달아주기 위한 껍데기같은 용도 인거죠??

**Comment by 100Gyeon** [comment]
넵 맞습니다!!
